#!/usr/bin/env python3
"""check-lockrules.py — make the two memory/lock rules a BUILD failure.

Both rules in this file were learned from panics, and both were written into
comments afterwards.  A comment does not fail a build, so each was violated
again by someone who had not read that particular file.  This turns them into
something the compiler run refuses to get past.

RULE A — nothing may allocate or free while a sched_lock is held.
  Holding a sched_lock across an allocation establishes a
  `sched_lock -> pmm_lock/kmalloc_lock` order that nothing else in the tree
  establishes.  With interrupts off it deadlocks against an IDLE core spinning
  inside the allocator, and surfaces as an amd64 K3-userland panic with a
  corrupted stack pointer — nowhere near the offending line.  This is why
  process_create_caps allocates its environment page BEFORE taking the lock.

RULE B — the mirror: a page must not be returned to the PMM while the running
  context still depends on it.
  Same idle core, other direction.  Freeing a kernel stack, a page-table tree
  or a PCB hands the page straight back to an allocator that another core is
  already spinning in, so the reuse is immediate rather than eventual.  A
  spilled callee-saved register reloaded from such a page comes back holding
  whatever the new owner wrote, which is how `frame->rip -= 2` ended up writing
  into kernel text.  A `pmm_free*` or `vmm_destroy_pgd` in a function that also
  reads `current_process` is where that goes wrong, so that combination is
  reported for review rather than trusted.

Both rules are TRANSITIVE, which is the whole point: the call that broke rule A
was `process_redirect_child_fd_from`, which does not itself contain the word
kmalloc — it calls `handles_ensure`, which does.  A checker that only looked
for literal allocator names one level deep would have passed that code.

  scripts/check-lockrules.py            report violations, exit 1 if any
  scripts/check-lockrules.py --list     list what it inferred, then report

Deliberately dependency-free: it is a build gate, so it must run everywhere the
build runs.  It is a text-level analysis, not a compiler — it can be fooled by
macros that hide a call, and it says so rather than claiming soundness.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Allocator/deallocator leaves.  Anything reaching these reaches the PMM or the
# kmalloc arena, which is the lock the rules are about.
ALLOC_LEAVES = {
    "kmalloc", "kfree", "kcalloc", "krealloc",
    "pmm_alloc_page", "pmm_alloc_pages", "pmm_free_page", "pmm_free_pages",
    "vmm_destroy_pgd", "vmm_create_pgd", "vmm_alloc_page",
}

# The subset of RULE A that is also RULE B: returning memory to the PMM.
FREE_LEAVES = {
    "pmm_free_page", "pmm_free_pages", "vmm_destroy_pgd",
}

LOCK_RE = re.compile(r"\bspin_lock(?:_irqsave)?\s*\(\s*&([A-Za-z0-9_>.\-]*sched_lock)")
UNLOCK_RE = re.compile(r"\bspin_unlock(?:_irqrestore)?\s*\(\s*&([A-Za-z0-9_>.\-]*sched_lock)")
# A function definition at column 0: `type name(args) {`.  Crude on purpose —
# this tree is plain C with K&R-style definitions at top level.
FUNC_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_ \*]*?\b([A-Za-z_][A-Za-z0-9_]*)\s*\([^;]*$")
CALL_RE = re.compile(r"\b([a-z_][a-z0-9_]*)\s*\(")

# Calls that look like calls but are not, or that carry no allocation.
NOT_CALLS = {"if", "for", "while", "switch", "return", "sizeof", "do",
             "case", "defined", "offsetof"}


def c_sources():
    for base, dirs, files in os.walk(os.path.join(ROOT, "kernel")):
        dirs[:] = [d for d in dirs if d not in ("build", ".git")]
        for f in files:
            if f.endswith(".c"):
                yield os.path.join(base, f)


def parse_functions(path):
    """Return [(name, start_line, [lines])] using brace depth.

    Text-level, so a function whose body is generated by a macro is invisible
    here.  That limit is reported by --list rather than hidden."""
    with open(path, "r", errors="replace") as fh:
        lines = fh.readlines()
    out = []
    i = 0
    while i < len(lines):
        m = FUNC_RE.match(lines[i])
        if not m or lines[i].lstrip().startswith(("#", "/", "*")):
            i += 1
            continue
        # find the opening brace within a few lines (multi-line arg lists)
        j, depth, started = i, 0, False
        while j < len(lines) and j < i + 12 and not started:
            if "{" in lines[j]:
                started = True
                break
            if ";" in lines[j]:  # a prototype, not a definition
                break
            j += 1
        if not started:
            i += 1
            continue
        body, k = [], j
        while k < len(lines):
            depth += lines[k].count("{") - lines[k].count("}")
            body.append(lines[k])
            if depth <= 0:
                break
            k += 1
        out.append((m.group(1), i + 1, body))
        i = k + 1
    return out


def calls_in(body):
    names = set()
    for ln in body:
        code = ln.split("//")[0]
        for c in CALL_RE.findall(code):
            if c not in NOT_CALLS:
                names.add(c)
    return names


def main():
    want_list = "--list" in sys.argv

    funcs = {}          # name -> (path, line, body)
    for path in c_sources():
        for name, line, body in parse_functions(path):
            funcs.setdefault(name, (path, line, body))

    # Transitive closure: a function "allocates" if it reaches an allocator
    # leaf through any number of in-tree calls.  Fixed point, so mutual
    # recursion terminates.
    allocating = set(ALLOC_LEAVES)
    freeing = set(FREE_LEAVES)
    changed = True
    while changed:
        changed = False
        for name, (_p, _l, body) in funcs.items():
            if name in allocating and name in freeing:
                continue
            called = calls_in(body)
            if name not in allocating and (called & allocating):
                allocating.add(name)
                changed = True
            if name not in freeing and (called & freeing):
                freeing.add(name)
                changed = True

    if want_list:
        print("reaches an allocator (%d):" % len(allocating))
        print("  " + ", ".join(sorted(allocating)))
        print()

    viol_a, viol_b = [], []
    for path, rel in ((p, os.path.relpath(p, ROOT)) for p in c_sources()):
        for name, line, body in parse_functions(path):
            # RULE A: walk the body tracking sched_lock depth.
            depth = 0
            for off, ln in enumerate(body):
                code = ln.split("//")[0]
                if LOCK_RE.search(code):
                    depth += 1
                    continue
                if UNLOCK_RE.search(code):
                    depth = max(0, depth - 1)
                    continue
                if depth > 0:
                    for c in CALL_RE.findall(code):
                        if c in NOT_CALLS or c not in allocating:
                            continue
                        why = ("allocates directly" if c in ALLOC_LEAVES
                               else "reaches an allocator transitively")
                        viol_a.append((rel, line + off, name, c, why))

            # RULE B: a PMM free in a function that also reads current_process.
            joined = "".join(body)
            called = calls_in(body)
            hot = called & FREE_LEAVES
            if hot and "current_process" in joined:
                for off, ln in enumerate(body):
                    for c in CALL_RE.findall(ln.split("//")[0]):
                        if c in FREE_LEAVES:
                            viol_b.append((rel, line + off, name, c))

    for f, l, fn, c, why in viol_a:
        print("RULE-A %s:%d: %s() calls %s() under sched_lock — %s"
              % (f, l, fn, c, why))
    for f, l, fn, c in viol_b:
        print("RULE-B %s:%d: %s() calls %s() and also reads current_process — "
              "confirm the running context no longer depends on that page"
              % (f, l, fn, c))

    n = len(viol_a) + len(viol_b)
    print("\ncheck-lockrules: %d rule-A, %d rule-B" % (len(viol_a), len(viol_b)))
    return 1 if n else 0


if __name__ == "__main__":
    sys.exit(main())
