#!/usr/bin/env python3
"""
scripts/gen-layering-cocci.py — generate the ASTRA layering gate (Phase 10a).

Coccinelle matches `#include` directives by EXACT string, not by regex over the
path, so a hand-written rule set would silently stop covering the boundary the
moment a header is added.  This generator derives the rules from the actual
inventory instead, so the gate cannot drift away from the tree:

  * every file under include/api and include/abi becomes a rule forbidding the
    KERNEL from including it;
  * every .c under kernel/lib becomes a rule forbidding USERLAND from compiling
    it as a source.

Run it whenever headers are added; check the generated .cocci in, so the diff
shows exactly what the boundary is at any commit.

Why coccinelle and not grep: the same file also carries the SEMANTIC rules
(below the generated section), which grep cannot express — and having one gate
rather than two means there is one place a violation has to get past.
"""

import os

API_DIRS = ("include/api", "include/abi")
KERNEL_LIB = "kernel/lib"
# TWO files, because the two directions must be checked against DIFFERENT
# trees.  `#include <os1.h>` is a violation in kernel/ and entirely correct in
# user/ — a single rule set applied to everything would condemn the userland
# headers doing their job.  The direction is the whole point, so it has to be
# encoded in WHAT gets scanned, not just in what is matched.
OUT_KERNEL = "scripts/layering-kernel.cocci"
OUT_USER = "scripts/layering-user.cocci"

HEADER = '''// scripts/layering.cocci — ASTRA layering gate (Phase 10a, directive 3)
//
// GENERATED by scripts/gen-layering-cocci.py — do not edit the generated
// section by hand; re-run the generator instead.
//
// Enforces mechanically the boundary the whole plan rests on: kernel and
// userland share NO compile-time coupling.  Information crosses the boundary
// as OBJECTS through the syscall dispatcher, which is what the dispatcher is
// for; a shared header makes the two sides one program that must be rebuilt
// together, which is the coupling being removed.
//
// Review has repeatedly failed to catch this class — USR-LIB-01 has been
// in-tree, flagged in a comment, and shipping for months — so the check has to
// be something the build runs, not something a reviewer is expected to notice.
//
// Usage: scripts/check-layering.sh   (non-empty output == violation)
'''


def emit_rules(out, title, includes, note):
    out.append("\n// ---------------------------------------------------------------------------")
    out.append("// %s" % title)
    out.append("// %s" % note)
    out.append("// ---------------------------------------------------------------------------")
    for i, inc in enumerate(includes):
        out.append("")
        out.append("@@")
        out.append("@@")
        out.append("")
        out.append("- #include %s" % inc)


def main():
    api_headers = []
    for d in API_DIRS:
        for root, _, files in os.walk(d):
            for f in sorted(files):
                if f.endswith(".h"):
                    rel = os.path.relpath(os.path.join(root, f), d)
                    api_headers.append(rel)
    api_headers = sorted(set(api_headers))

    kernel_sources = sorted(
        f for f in os.listdir(KERNEL_LIB) if f.endswith(".c")
    )

    # --- direction 1: scanned against kernel/ ONLY -------------------------
    out = [HEADER]
    incs = ["<%s>" % h for h in api_headers]
    # The quoted relative escapes two kernel headers use today are not
    # reachable by the angled form, so they need their own exact rules.
    incs += ['"../../../../include/api/%s"' % h for h in api_headers]
    incs += ['"../../../../include/abi/%s"' % h for h in api_headers]
    emit_rules(
        out,
        "the KERNEL must not include a USERLAND header",
        incs,
        "Enabled today by Makefile:101 giving the kernel -Iinclude/abi -Iinclude/api.",
    )
    with open(OUT_KERNEL, "w") as f:
        f.write("\n".join(out) + "\n")

    # --- direction 2: scanned against user/ ONLY ---------------------------
    out = [HEADER]
    incs = []
    for src in kernel_sources:
        for depth in ("../", "../../", "../../../", "../../../../"):
            incs.append('"%s%s/%s"' % (depth, KERNEL_LIB, src))
    incs += ["<kernel/%s>" % h for h in ("sched.h", "object.h", "vfs.h",
                                         "registry.h", "types.h", "string.h",
                                         "kmalloc.h", "printk.h", "vmm.h")]
    emit_rules(
        out,
        "USERLAND must not compile or include KERNEL code",
        incs,
        "USR-LIB-01: those files carry #ifdef KERNEL sites, so userland gets the "
        "non-kernel half of a KERNEL file — one file that is two implementations.",
    )
    with open(OUT_USER, "w") as f:
        f.write("\n".join(out) + "\n")

    print("wrote %s + %s: %d api/abi headers, %d kernel sources"
          % (OUT_KERNEL, OUT_USER, len(api_headers), len(kernel_sources)))


if __name__ == "__main__":
    main()
