#!/usr/bin/env python3
"""Official NexsOS1 Coreutils inventory audit.

This script verifies the real GNU coreutils program set against the binaries that
are actually packaged in NexsOS1's rootfs. It deliberately compares the upstream
list generated by coreutils itself with the installed user-space binaries, and it
normalizes names like "cu_echo" -> "echo" so the result reflects the real public
surface.

Exit status:
  0 = all upstream programs are present in the rootfs
  1 = one or more programs are missing, or the upstream build metadata is not
      available
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def run(cmd: list[str], cwd: Path | None = None) -> str:
    proc = subprocess.run(cmd, cwd=str(cwd) if cwd else None, text=True, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(f"command failed ({proc.returncode}): {' '.join(cmd)}\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}")
    return proc.stdout


def upstream_programs(repo_root: Path) -> set[str]:
    coreutils_dir = repo_root / "user" / "bin" / "coreutils"
    if not coreutils_dir.is_dir():
        raise FileNotFoundError(f"missing coreutils source tree: {coreutils_dir}")
    script = coreutils_dir / "build-aux" / "gen-lists-of-programs.sh"
    if not script.exists():
        raise FileNotFoundError(f"missing coreutils list generator: {script}")
    out = run(["bash", str(script), "--list-progs"], cwd=coreutils_dir)
    names = {line.strip() for line in out.splitlines() if line.strip()}
    return names


def installed_programs(rootfs_dir: Path) -> set[str]:
    names: set[str] = set()
    for search_root in (rootfs_dir / "bin", rootfs_dir / "sys" / "bin"):
        if not search_root.is_dir():
            continue
        for entry in search_root.iterdir():
            if not entry.is_file():
                continue
            name = entry.name
            names.add(name)
            if name.startswith("cu_"):
                names.add(name[3:])
    return names


def main() -> int:
    parser = argparse.ArgumentParser(description="Official NexsOS1 Coreutils audit")
    parser.add_argument("--arch", default=os.environ.get("ARCH", "amd64"), help="target architecture (amd64 or aarch64)")
    parser.add_argument("--repo-root", default=str(Path(__file__).resolve().parents[1]), help="path to NexsOS1 repository root")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    arch = args.arch
    rootfs_dir = repo_root / "build" / arch / "rootfs"
    if not rootfs_dir.is_dir():
        print(f"ERROR: missing rootfs for arch '{arch}': {rootfs_dir}")
        return 2

    try:
        upstream = upstream_programs(repo_root)
        installed = installed_programs(rootfs_dir)
    except Exception as exc:  # pragma: no cover - user-facing validation path
        print(f"ERROR: {exc}")
        return 2

    missing = sorted(upstream - installed)
    present = sorted(upstream & installed)

    print("NexsOS1 Coreutils official audit")
    print(f"arch: {arch}")
    print(f"upstream programs: {len(upstream)}")
    print(f"available in rootfs: {len(present)}")
    print(f"missing from rootfs: {len(missing)}")

    if missing:
        print("missing:")
        for name in missing:
            print(f"  - {name}")
        print("")
        print("status: FAIL")
        return 1

    print("status: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
