# user/sys/lib/portability/gnulib/overlay.mk
# Gnulib build overlay for NexsOS1

GNULIB_PORT_DIR   := user/sys/lib/portability/gnulib
GNULIB_DIR        := user/sys/lib/gnulib
COREUTILS_PORT_DIR := user/sys/lib/portability/coreutils
COREUTILS_DIR     := user/bin/coreutils
COREUTILS_SRC_DIR := $(COREUTILS_DIR)/src

GNULIB_OVERLAY_SRCS := \
  $(GNULIB_PORT_DIR)/gnulib_os1_glue.c \
  $(GNULIB_PORT_DIR)/hard_locale_compat.c \
  $(GNULIB_PORT_DIR)/locale_compat.c \
  $(GNULIB_DIR)/lib/basename-lgpl.c \
  $(GNULIB_DIR)/lib/dirname-lgpl.c \
  $(GNULIB_DIR)/lib/basename.c \
  $(GNULIB_DIR)/lib/dirname.c \
  $(GNULIB_DIR)/lib/argmatch.c \
  $(GNULIB_DIR)/lib/stripslash.c \
  $(GNULIB_DIR)/lib/c-ctype.c \
  $(GNULIB_DIR)/lib/c-strcasecmp.c \
  $(GNULIB_DIR)/lib/c-strncasecmp.c \
  $(GNULIB_DIR)/lib/c-strtod.c \
  $(GNULIB_DIR)/lib/c-strtold.c \
  $(GNULIB_DIR)/lib/exitfail.c \
  $(GNULIB_DIR)/lib/inttostr.c \
  $(GNULIB_DIR)/lib/imaxtostr.c \
  $(GNULIB_DIR)/lib/umaxtostr.c \
  $(GNULIB_DIR)/lib/offtostr.c \
  $(GNULIB_DIR)/lib/bitrotate.c \
  $(GNULIB_DIR)/lib/gl_list.c \
  $(GNULIB_DIR)/lib/gl_array_list.c \
  $(GNULIB_DIR)/lib/gl_linked_list.c \
  $(GNULIB_DIR)/lib/progname.c \
  $(GNULIB_DIR)/lib/version-etc.c \
  $(GNULIB_DIR)/lib/version-etc-fsf.c \
  $(GNULIB_DIR)/lib/closeout.c \
  $(GNULIB_DIR)/lib/close-stream.c \
  $(GNULIB_DIR)/lib/quotearg.c \
  $(GNULIB_DIR)/lib/xalloc-die.c \
  $(GNULIB_DIR)/lib/xmalloc.c \
  $(GNULIB_DIR)/lib/xstrndup.c \
  $(GNULIB_DIR)/lib/xvasprintf.c \
  $(GNULIB_DIR)/lib/xasprintf.c \
  $(GNULIB_DIR)/lib/getopt.c \
  $(GNULIB_DIR)/lib/getopt1.c \
  $(GNULIB_DIR)/lib/long-options.c \
  $(GNULIB_DIR)/lib/xgetcwd.c \
  $(GNULIB_DIR)/lib/argv-iter.c \
  $(GNULIB_DIR)/lib/obstack.c \
  $(GNULIB_DIR)/lib/readtokens0.c \
  $(GNULIB_DIR)/lib/timespec.c \
  $(GNULIB_DIR)/lib/gettime.c \
  $(GNULIB_DIR)/lib/posixtm.c \
  $(GNULIB_PORT_DIR)/parse-datetime.c \
  $(GNULIB_DIR)/lib/utime.c \
  $(GNULIB_DIR)/lib/utimens.c \
  $(GNULIB_DIR)/lib/utimensat.c \
  $(GNULIB_DIR)/lib/futimens.c \
  $(GNULIB_DIR)/lib/fdutimensat.c \
  $(GNULIB_DIR)/lib/save-cwd.c \
  $(GNULIB_DIR)/lib/openat-proc.c \
  $(GNULIB_DIR)/lib/openat-die.c \
  $(GNULIB_DIR)/lib/btoc32.c \
  $(GNULIB_DIR)/lib/c32width.c \
  $(GNULIB_DIR)/lib/c32_get_type_test.c \
  $(GNULIB_DIR)/lib/c32_apply_type_test.c \
  $(GNULIB_DIR)/lib/localeinfo.c \
  $(GNULIB_DIR)/lib/malloc/dynarray_resize.c \
  $(GNULIB_DIR)/lib/malloc/dynarray_resize_clear.c \
  $(COREUTILS_DIR)/gl/lib/root-dev-ino.c \
  $(COREUTILS_DIR)/gl/lib/xfts.c \
  $(COREUTILS_DIR)/gl/lib/fadvise.c \
  $(COREUTILS_DIR)/gl/lib/cl-strtod.c \
  $(COREUTILS_DIR)/gl/lib/cl-strtold.c \
  $(GNULIB_DIR)/lib/alignalloc.c \
  $(GNULIB_DIR)/lib/xalignalloc.c \
  $(GNULIB_DIR)/lib/dtotimespec.c \
  $(GNULIB_DIR)/lib/xnanosleep.c \
  $(GNULIB_DIR)/lib/full-read.c \
  $(GNULIB_DIR)/lib/full-write.c \
  $(GNULIB_DIR)/lib/safe-read.c \
  $(GNULIB_DIR)/lib/safe-write.c \
  $(GNULIB_DIR)/lib/modechange.c \
  $(GNULIB_DIR)/lib/filemode.c \
  $(GNULIB_DIR)/lib/mkdir-p.c \
  $(GNULIB_DIR)/lib/mkancesdirs.c \
  $(GNULIB_DIR)/lib/dirchownmod.c \
  $(GNULIB_DIR)/lib/savewd.c \
  $(GNULIB_DIR)/lib/propername-lite.c \
  $(GNULIB_DIR)/lib/xstrtol.c \
  $(GNULIB_DIR)/lib/xstrtoll.c \
  $(GNULIB_DIR)/lib/xstrtold.c \
  $(GNULIB_DIR)/lib/xstrtoul.c \
  $(GNULIB_DIR)/lib/xstrtoull.c \
  $(GNULIB_DIR)/lib/xstrtoumax.c \
  $(GNULIB_DIR)/lib/xstrtoimax.c \
  $(GNULIB_DIR)/lib/xstrtol-error.c \
  $(GNULIB_DIR)/lib/xbinary-io.c \
  $(GNULIB_DIR)/lib/human.c \
  $(GNULIB_DIR)/lib/base64.c \
  $(GNULIB_DIR)/lib/base32.c \
  $(GNULIB_DIR)/lib/md5.c \
  $(GNULIB_DIR)/lib/sha1.c \
  $(GNULIB_DIR)/lib/sha256.c \
  $(GNULIB_DIR)/lib/hash.c \
  $(COREUTILS_DIR)/gl/lib/fadvise.c \
  $(GNULIB_DIR)/lib/fd-safer.c \
  $(GNULIB_DIR)/lib/fopen-safer.c \
  $(GNULIB_DIR)/lib/freopen-safer.c \
  $(GNULIB_DIR)/lib/open-safer.c \
  $(GNULIB_DIR)/lib/dup-safer.c \
  $(GNULIB_DIR)/lib/pipe-safer.c \
  $(GNULIB_DIR)/lib/memset_explicit.c \
  $(GNULIB_DIR)/lib/next-prime.c \
  $(GNULIB_DIR)/lib/userspec.c \
  $(GNULIB_DIR)/lib/memmem.c \
  $(GNULIB_DIR)/lib/memchr2.c \
  $(GNULIB_DIR)/lib/physmem.c \
  $(GNULIB_DIR)/lib/nproc.c \
  $(GNULIB_DIR)/lib/getdelim.c \
  $(GNULIB_DIR)/lib/linebuffer.c \
  $(GNULIB_DIR)/lib/read-file.c \
  $(GNULIB_DIR)/lib/readutmp.c \
  $(GNULIB_DIR)/lib/readtokens.c \
  $(GNULIB_DIR)/lib/str_endswith.c \
  $(GNULIB_DIR)/lib/stdc_leading_zeros.c \
  $(GNULIB_DIR)/lib/stdc_trailing_zeros.c \
  $(GNULIB_DIR)/lib/mini-gmp-gnulib.c \
  $(GNULIB_DIR)/lib/hashcode-string2.c \
  $(GNULIB_DIR)/lib/file-set.c \
  $(GNULIB_DIR)/lib/hashcode-named-file.c \
  $(GNULIB_DIR)/lib/hashcode-file-inode.c \
  $(GNULIB_DIR)/lib/canonicalize.c \
  $(GNULIB_DIR)/lib/areadlink-with-size.c \
  $(GNULIB_DIR)/lib/regex.c \
  $(GNULIB_DIR)/lib/malloc/scratch_buffer_grow.c \
  $(GNULIB_DIR)/lib/malloc/scratch_buffer_grow_preserve.c \
  $(GNULIB_DIR)/lib/malloc/scratch_buffer_set_array_size.c \
  $(COREUTILS_DIR)/gl/lib/rand-isaac.c \
  $(COREUTILS_DIR)/gl/lib/randint.c \
  $(COREUTILS_DIR)/gl/lib/randperm.c \
  $(COREUTILS_DIR)/gl/lib/randread.c \
  $(COREUTILS_DIR)/gl/lib/xdectoimax.c \
  $(COREUTILS_DIR)/gl/lib/xdectoumax.c \
  $(COREUTILS_DIR)/gl/lib/buffer-lcm.c \
  $(COREUTILS_DIR)/gl/lib/fd-reopen.c \
  $(COREUTILS_DIR)/gl/lib/strintcmp.c \
  $(COREUTILS_DIR)/gl/lib/strnumcmp.c \
  $(GNULIB_DIR)/lib/filenamecat-lgpl.c \
  $(GNULIB_DIR)/lib/filenamecat.c \
  $(GNULIB_DIR)/lib/mbrtowc.c \
  $(GNULIB_DIR)/lib/mbrlen.c \
  $(GNULIB_DIR)/lib/memcasecmp.c \
  $(GNULIB_DIR)/lib/fprintftime.c \
  $(COREUTILS_SRC_DIR)/prog-fprintf.c

GNULIB_OVERLAY_CONFIG := $(GNULIB_PORT_DIR)/gnulib_config_nexsos.h

GNULIB_OVERLAY_CPPFLAGS := -D__NEXSOS__ -DFLEXIBLE_ARRAY_MEMBER= -I$(GNULIB_PORT_DIR) -I$(COREUTILS_PORT_DIR) -I$(GNULIB_DIR)/lib -I$(COREUTILS_DIR)/gl/lib -I$(COREUTILS_DIR)/src -include $(GNULIB_OVERLAY_CONFIG)
